source("Load_data.R")
PowerS <- load_data()
png("plot1.png", width=400, height=400)
hist(PowerS$Global_active_power, main = "Global Active Power", xlab = "Global Active Power (kilowatts)", col ="red")
dev.off()